# Dependencies

#highlighter:      pygments
markdown:         kramdown 
highlighter:      rouge

line_numbers: true

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Hong
tagline:          'A Jekyll theme'
description:      ''
url:              /
baseurl:          /

exclude:
  - "run.bat"

gems:
 - jekyll-paginate
 - jekyll-gist 

author:
  name:           'Hong'
  url:            https://twitter.com/hong0102

paginate:         20

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/hongdiablo/hongdiablo.github.io.git



