# Dependencies
markdown:         kramdown 
#highlighter:      pygments
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Hong
tagline:          'A Jekyll theme'
description:      ''
url:              /
baseurl:          /

gems:
 - jekyll-paginate
 - jekyll-gist 

author:
  name:           'Hong'
  url:            https://twitter.com/hong0102

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/hongdiablo/hongdiablo.github.io.git
